# 403
POST http://localhost:8080/sign-in
Content-Type: application/json

{
  "email": "invalid@email.com",
  "password": "invalid password"
}

###
# 200
POST http://localhost:8080/sign-in
Content-Type: application/json

{
  "email": "test@account",
  "password": "password"
}
> {% client.global.set("Player-Authorization", response.body.accessToken); %}


###
# 200
GET http://localhost:8080/test-authorize
Player-Authorization: {{Player-Authorization}}
Content-Type: application/json

###
# 403
GET http://localhost:8080/test2
player_authorization: Bearer "invalid jwt"
Content-Type: application/json

###
