# 403
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "invalid@email.com",
  "password": "invalid password"
}

###
# 200
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "test@account",
  "password": "password"
}
> {% client.global.set("auth_token", response.body.accessToken); %}

###
# 200
GET http://localhost:8080/test-authorize
Authorization: Bearer {{auth_token}}
Content-Type: application/json

###
# 403
GET http://localhost:8080/test-authorize
Authorization: Bearer "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0QGFjY291bnQiLCJpYXQiOjE2MTAyOTkyMTcsImV4cCI6MTYxMDM4NTYxN30"
Content-Type: application/json

###
